In [8]:
from scipy.io import loadmat
import pandas as pd
from glob import glob
from datetime import datetime as dt
import numpy as np

In [23]:
date_i_want = dt(2022, 8, 1, 0, 0, 0)
tfmtime = np.array([date_i_want, date_i_want.replace(hour=23, minute=59, second=59)]).astype('datetime64[s]')

In [4]:
guy_ccn_data = pd.DataFrame()

In [5]:
for file_path in glob('/Volumes/LtgSSD/guy-ccn/*.mat'):
    guy_ccn = loadmat(file_path)
    varnames = guy_ccn['CCN'][0][0].dtype.names
    data_dict = {varname: guy_ccn['CCN'][0][0][varname].flatten() for varname in varnames}
    guy_ccn_data = pd.concat([guy_ccn_data, pd.DataFrame(data_dict)])

In [6]:
guy_ccn_data['time'] = pd.to_datetime(guy_ccn_data['UTC']-719529, unit='D')
guy_ccn_data = guy_ccn_data.set_index('time', drop=True)

In [22]:
guy_ccn_data.index.values

array(['2022-07-02T18:23:31.559996008', '2022-07-02T18:23:32.650002165',
       '2022-07-02T18:23:33.970001043', ...,
       '2022-09-10T19:10:24.920002744', '2022-09-10T19:10:25.919997320',
       '2022-09-10T19:10:26.920001953'], dtype='datetime64[ns]')

In [28]:
np.unique(guy_ccn_data.SS_set)

array([0.13, 0.35, 0.47, 0.63, 0.8 ])

In [29]:
guy_ccn_04 = guy_ccn_data[guy_ccn_data['SS_set'] == 0.47]

In [30]:
guy_ccn_06 = guy_ccn_data[guy_ccn_data['SS_set'] == 0.63]

In [31]:
guy_ccn_04

,DT_ccn,Pabs_ccn,Q_sh_ccn,Q_smp_ccn,T1_ccn,T2_ccn,T3_ccn,T_Naf_ccn,T_OPC_ccn,T_inlet_ccn,T_smp_ccn,laserI_ccn,n0_all_ccn,raw_counts_ccn,stage1_ccn,UTC,SS_set
time,,,,,,,,,,,,,,,,,
2022-07-02 18:29:35.860001521,8,999.31,453.80,44.70,26.71,31.68,35.85,25.56,37.85,27.51,23.98,91.48,NaN,355.014850,0.68,738704.770554,0.47
2022-07-02 18:29:36.790000494,8,999.21,455.14,44.80,26.73,31.71,35.85,25.57,37.82,27.53,24.00,91.48,NaN,349.029333,0.67,738704.770565,0.47
2022-07-02 18:29:37.840004859,8,999.16,450.58,44.47,26.71,31.60,35.74,25.58,37.79,27.53,23.99,91.48,NaN,341.989123,0.68,738704.770577,0.47
2022-07-02 18:29:38.799997644,8,999.09,454.87,44.72,26.71,31.47,35.67,25.55,37.74,27.53,24.00,91.37,NaN,349.017240,0.68,738704.770588,0.47
2022-07-02 18:29:39.790004346,8,999.27,453.93,45.18,26.70,31.29,35.47,25.58,37.73,27.52,23.98,91.48,NaN,392.983170,0.68,738704.770599,0.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-10 18:52:08.889999168,8,997.99,455.67,44.76,30.07,34.00,37.38,28.91,39.38,30.85,27.80,94.13,NaN,5094.314640,0.66,738774.786214,0.47
2022-09-10 18:52:09.890003801,8,998.50,457.82,45.24,30.07,34.02,37.40,28.95,39.37,30.90,27.85,94.24,6620.57,4991.909780,0.65,738774.786226,0.47
2022-09-10 18:52:10.889998377,8,998.44,454.33,45.11,30.08,33.99,37.36,28.94,39.35,30.87,27.84,94.24,6648.71,4998.721802,0.66,738774.786237,0.47
2022-09-10 18:52:11.890003010,8,998.43,458.22,45.08,30.01,34.00,37.38,28.93,39.32,30.92,27.83,94.18,6770.19,5086.669420,0.66,738774.786249,0.47
2022-09-10 18:52:12.929999378,8,998.31,455.00,44.78,30.04,34.03,37.34,28.95,39.29,30.93,27.85,94.07,NaN,4967.340913,0.66,738774.786261,0.47